# Generated by Django 4.0.1 on 2022-01-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('about', models.TextField()),
                ('facebook_profile', models.URLField(max_length=254)),
                ('linkedin_profile', models.URLField(max_length=254)),
                ('twitter_profile', models.URLField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
